sonar.projectKey=dsantacruza101_telegram-bot
sonar.organization=dsantacruza101
sonar.sources=.
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/*.save,venv/**,.venv-dev/**,tests/**,**/*.pyc
sonar.test.inclusions=tests/**
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
